### ISSUE TITLE
Suggestion: Specify what to keep (exceptions)

### ISSUE THREAD

**Issue by OndrejSpanel** [yumemi-inc/clean-cache-action#83]
I would like to use this action to perform regular cache cleanup from within the branch push. For that purpose it would be handy to be able to specify what entries should be left in cache:
- number of most recent entries to always keep
- a key (or a list of keys) to be kept

```
  except:
    description: Key which should not be deleted
  keep:
    description: Number of most recent items to keep
    default: '0'
```

Implementing both should be easy, the entries are already returned in suitable order and have their keys accessible.
